name: real_estate_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  get_cli: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/



  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: asset/fonts/Poppins-Regular.ttf
        - asset: asset/fonts/Poppins-SemiBold.ttf
          weight: 600




